config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user do
    collection do
      get 'report'
      get 'search'
      get 'excel'
    end
  end
  resources :stores
  resources :issues

  namespace :api do
    post '/user/login' => 'users#login'
    post '/user/logout' => 'users#logout'
    get '/user/stores' => 'users#stores'
    get '/user/store/:store_id/issues' => 'users#issues'
    post '/user/store/:store_id/save_issue_qty' => 'users#save_issue_qty'
    post '/user/store/:store_id/payment' => 'users#payment'
  end

  root 'stores#index'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	validates_uniqueness_of :name
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_issue, only: [:show, :edit, :update, :destroy]

	def index
  		@issues = Issue.all
	end

	def new
		@issue = Issue.new
	end

	def create
		@issue = Issue.new(issue_params)
		if @issue.save
			redirect_to issues_url, notice: "Issue was successfully created."
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @issue.update(issue_params)
	    	redirect_to issues_url, notice: 'Issue was successfully updated.'
	    else
	    	render :edit
	    end
	end

	def show
		
	end

	def destroy
		Store.where(current_issue_id: @issue.id).update_all(drop_qty: nil, pick_qty:nil, current_issue_id: nil)
		@issue.destroy
		redirect_to issues_url, notice: 'Issue was successfully deleted.'
	end

	private

	def set_issue
      @issue = Issue.find(params[:id])
    end

	def issue_params
		params.require(:issue).permit(:name, :quantity, :amount)
	end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<div class="page-header">
  <h1 class="page-title">Add Issue</h1>
</div>
<div class="page-content">
  <div class="panel">
    <div class="panel-body">
      <%= form_for(@issue,url: (@issue.new_record? ? issues_path : issue_path), html: {class: "form-horizontal", id: "issue_form"}) do |f| %>
          <% if @issue.errors.any? %>
            <div class="alert dark alert-danger alert-dismissible">
              <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

              <ul>
              <% @issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name,"Id", class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <!-- <div class="form-group">
            <%#= f.label :quantity, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%#= f.number_field :quantity, autofocus: true, class: "form-control" %>
            </div>
          </div> -->

          <div class="form-group">
            <%= f.label :amount, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.number_field :amount, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
                  <%= f.submit (@issue.new_record? ? "Submit" : "Update"), class: "btn btn-primary", id: "validateButton" %>
                   <%= link_to 'Back', issues_path, class: "btn btn-primary", method: "get" %>
              </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#issue_form').formValidation({
      framework: "bootstrap",
      button: {
        selector: '#validateButton',
        disabled: 'disabled'
      },
      icon: null,
      fields: {
        "issue[name]": {
          validators: {
            notEmpty: {
              message: 'The name is required and cannot be empty'
            }
          }
        }
      }
    });
  })
</script>

app/views/issues/edit.html.erb
<%= render 'form' %>

app/views/issues/index.html.erb
<div class="page-header">
  <h1 class="page-title">Issues <%= link_to 'Add Issue', new_issue_path, class: "btn btn-primary pull-right", method: :get %></h1>
</div>
<div class="page-content">
	<div class="panel">
        <div class="panel-body">
        	<table class="table table-hover dataTable table-striped width-full" data-plugin="dataTable" id="issue_table">
	            <thead>
	              <tr>
	                <th>ID</th>
	                <!-- <th>Quantity</th> -->
	                <!-- <th>Price</th> -->
					<th>Actions</th>
					<th>Actions</th>
	              </tr>
	            </thead>
	            <tbody>
	            	<% @issues.each do |u| %>
						<tr>
							<td><%= u.name %></td>
							<!-- <td><%#= u.quantity %></td> -->
							<!-- <td><%#= u.amount %></td> -->
							<td><%= link_to 'Edit', edit_issue_path(u), method: :get %></td>
					        <td><%= link_to 'Delete', issue_path(u), method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
					<% end %>
            	</tbody>
          	</table>
        </div>
  	</div>
</div>

app/views/issues/new.html.erb
<%= render 'form' %>

app/views/issues/show.html.erb
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @issue.name %>
	</p>

	<%= link_to 'Edit', edit_issue_path(@issue) %> |
	<%= link_to 'Back', issues_path %>
</div>