config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user do
    collection do
      get 'report'
      get 'search'
      get 'excel'
    end
  end
  resources :stores
  resources :issues

  namespace :api do
    post '/user/login' => 'users#login'
    post '/user/logout' => 'users#logout'
    get '/user/stores' => 'users#stores'
    get '/user/store/:store_id/issues' => 'users#issues'
    post '/user/store/:store_id/save_issue_qty' => 'users#save_issue_qty'
    post '/user/store/:store_id/payment' => 'users#payment'
  end

  root 'stores#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
	attr_accessor :address

	def address
		"#{self.address_1} #{self.address_2} #{self.city} #{self.state} #{self.zip}"
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action :authenticate_user!
	before_action :set_store, only: [:show, :edit, :update, :destroy]

	def index
  		@stores = Store.all
	end

	def new
		@store = Store.new
	end

	def create
		@store = Store.new(store_params)
		if @store.save
			redirect_to stores_url, notice: "Store was successfully created."
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @store.update(store_params)
	    	redirect_to stores_url, notice: 'Store was successfully updated.'
	    else
	    	render :edit
	    end
	end

	def show
		
	end

	def destroy
		@store.destroy
		redirect_to stores_url, notice: 'Store was successfully deleted.'
	end

	private

	def set_store
      @store = Store.find(params[:id])
    end

	def store_params
		params.require(:store).permit(:name, :address_1, :address_2, :city, :state, :zip)
	end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<div class="page-header">
  <h1 class="page-title">Add Store</h1>
</div>
<div class="page-content">
  <div class="panel">
    <div class="panel-body">
      <%= form_for(@store,url: (@store.new_record? ? stores_path : store_path), html: {class: "form-horizontal", id: "store_form"}) do |f| %>
          <% if @store.errors.any? %>
            <div class="alert dark alert-danger alert-dismissible">
              <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

              <ul>
              <% @store.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :address_1, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :address_1, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :address_2, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :address_2, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :city, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :city, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :state, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :state, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :zip, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :zip, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
                  <%= f.submit (@store.new_record? ? "Submit" : "Update"), class: "btn btn-primary", id: "validateButton" %>
                   <%= link_to 'Back', stores_path, class: "btn btn-primary", method: "get" %>
              </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#store_form').formValidation({
      framework: "bootstrap",
      button: {
        selector: '#validateButton',
        disabled: 'disabled'
      },
      icon: null,
      fields: {
        "store[name]": {
          validators: {
            notEmpty: {
              message: 'The name is required and cannot be empty'
            }
          }
        },
        "store[address_1]": {
          validators: {
            notEmpty: {
              message: 'The address is required and cannot be empty'
            }
          }
        },
        "store[address_2]": {
          validators: {
            notEmpty: {
              message: 'The address is required and cannot be empty'
            }
          }
        },
        "store[city]": {
          validators: {
            notEmpty: {
              message: 'The city is required and cannot be empty'
            }
          }
        },
        "store[state]": {
          validators: {
            notEmpty: {
              message: 'The state is required and cannot be empty'
            }
          }
        },
        "store[zip]": {
          validators: {
            notEmpty: {
              message: 'The zip is required and cannot be empty'
            }
          }
        }
      }
    });
  })
</script>

app/views/stores/edit.html.erb
<%= render 'form' %>

app/views/stores/index.html.erb
<div class="page-header">
  <h1 class="page-title">Stores <%= link_to 'Add Store', new_store_path, class: "btn btn-primary pull-right", method: :get %></h1>
</div>
<div class="page-content">
	<div class="panel">
        <div class="panel-body">
        	<table class="table table-hover dataTable table-striped width-full" data-plugin="dataTable" id="store_table">
	            <thead>
	              <tr>
	                <th>Name</th>
					<th>Address</th>
					<th>Actions</th>
					<th>Actions</th>
	              </tr>
	            </thead>
	            <tbody>
	            	<% @stores.each do |u| %>
						<tr>
							<td><%= u.name %></td>
							<td><%= u.address %></td>
							<td><%= link_to 'Edit', edit_store_path(u), method: :get %></td>
					        <td><%= link_to 'Delete', store_path(u), method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
					<% end %>
            	</tbody>
          	</table>
        </div>
  	</div>
</div>

app/views/stores/new.html.erb
<%= render 'form' %>

app/views/stores/show.html.erb
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @store.name %>
	</p>

	<p>
	  <strong>Address:</strong>
	  <%= @store.address %>
	</p>

	<%= link_to 'Edit', edit_store_path(@store) %> |
	<%= link_to 'Back', stores_path %>
</div>