config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user do
    collection do
      get 'report'
      get 'search'
      get 'excel'
    end
  end
  resources :stores
  resources :issues

  namespace :api do
    post '/user/login' => 'users#login'
    post '/user/logout' => 'users#logout'
    get '/user/stores' => 'users#stores'
    get '/user/store/:store_id/issues' => 'users#issues'
    post '/user/store/:store_id/save_issue_qty' => 'users#save_issue_qty'
    post '/user/store/:store_id/payment' => 'users#payment'
  end

  root 'stores#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def self.authenticate(email, password)
        user = User.find_for_authentication(:email => email)
        user.valid_password?(password) ? user : nil
    end

    def generate_token
        token = SecureRandom.urlsafe_base64
        self.update_attributes(auth_token: token)
    end

    def clear_token
        self.update_attributes(auth_token: nil)
    end
    # def self.to_csv
    # binding.pry
      # CSV.generate do |csv|
      #   csv << column_names
      #   all.each do |product|
      #     csv << product.attributes.values_at(*column_names)
      #   end
      # end
    # end
    # def to_csv(options = Hash.new)
    #     binding.pry
    #     # override only if first element actually has as_csv method
    #     return old_to_csv(options) unless self.first.respond_to? :as_csv
    #     # use keys from first row as header columns
    #     out = first.as_csv.keys.to_csv(options)
    #     self.each { |r| out << r.as_csv.values.to_csv(options) }
    #     out
    # end
    def self.to_csv(options = {})
        binding.pry
        CSV.generate(options) do |csv|
        csv << column_names
        all.each do |product|
             csv << product.attributes.values_at(*column_names)
        end
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
	before_action :check_auth_token, only: [:logout, :stores, :issues, :save_issue_qty, :payment]

	def login
		user = User.authenticate(params[:user][:email], params[:user][:password])
		if user.blank?
			render :json => {data: user, status: 0, message: "Login Unsuccessfull. No user found."}
		else
			if user.auth_token.blank?
				user.generate_token
				render :json => {data: user, status: 1, message: "Login Successfull."}
			else
				render :json => {status: 0, message: "Already Logged In. Please logout from other devices."}
			end
		end
	end

	def logout
		@user.clear_token
		render :json => {status: 1, message: "Logout Successfull."}
	end

	def stores
		stores = Store.all
		render :json => {data: stores, status: 1}
	end

	def issues
		@store = Store.where(id: params[:store_id]).first
		if @store.blank?
			render :json => {status: 0, message: "No Store Found."}
		else
			# @data = Sale.where(user_id: @user.id, store_id: @store.id).first
			# if @data.blank?
			# 	last_issue_drop_qty = 0
			# 	last_issue_picked_id = ""
			# 	current_issue_drop_id = Issue.last.id
			# 	current_issue_drop_ref_id = Issue.last.try(:name)
			# else
			# 	last_issue_drop_qty = @data.drop_qty
			# 	last_issue_picked_id = @data.issue_id
			# 	last_issue_picked_ref_id = Issue.where(id: @data.issue_id).first.name
			# 	current_issue_drop_id = Issue.last.id
			# 	current_issue_drop_ref_id = Issue.last.try(:name)
			# end
			# render :json => { last_issue_drop_qty: last_issue_drop_qty, current_issue_drop_id: current_issue_drop_id, current_issue_drop_ref_id: current_issue_drop_ref_id,
			#  last_issue_picked_id: last_issue_picked_id,last_issue_picked_ref_id: last_issue_picked_ref_id}


			 render :json => { 
			 	store_id: @store.id,
			 	last_issue_drop_qty: @store.drop_qty,
			 	current_issue_drop_id: Issue.last.try(:id), 
			 	current_issue_drop_name: Issue.last.try(:name), 
			 	last_issue_picked_id: @store.current_issue_id,
			 	last_issue_picked_name: Issue.where(id: @store.current_issue_id ).first.try(:name)}
		end
	end

	def save_issue_qty
		@store = Store.where(id: params[:store_id]).first
		data = Sale.where(user_id: @user.id, store_id: @store.id)
		unless params[:data][:current_issue_drop_id].blank?
			obj=data.find_or_create_by(issue_id: params[:data][:current_issue_drop_id])
			obj.issue_id = params[:data][:current_issue_drop_id]
			obj.drop_qty = obj.drop_qty+params[:data][:current_issue_drop_qty].to_i
			obj.save
		end

		issue = Sale.where(store_id: @store.id, issue_id: params[:data][:last_issue_picked_id]).first

		if issue.blank?
			unless params[:data][:last_issue_picked_id].blank?
				obj=data.find_or_create_by(issue_id: params[:data][:last_issue_picked_id])
				obj.issue_id = params[:data][:last_issue_picked_id]
				obj.pick_qty = obj.pick_qty + params[:data][:last_picked_issue_qty].to_i
				obj.save
			end
		else
			issue.pick_qty = issue.pick_qty + params[:data][:last_picked_issue_qty].to_i
			issue.save
		end
		
		if @store.current_issue_id.to_i == params[:data][:current_issue_drop_id].to_i
			@store.drop_qty = @store.drop_qty + params[:data][:current_issue_drop_qty].to_i
		else
			@store.drop_qty = params[:data][:current_issue_drop_qty].to_i
		end
		@store.current_issue_id = params[:data][:current_issue_drop_id]
		@store.save

		issue = obj if issue.blank?
		sale_issue_qty = issue.drop_qty.to_i - issue.pick_qty.to_i
		amount = Issue.find(issue.issue_id).amount.to_f*sale_issue_qty
		amount = 0 if Issue.all.count < 2
		render :json => {status: 1, amount: amount}
	end

	def payment
		data = Sale.where(user_id: @user.id, store_id: params[:store_id], issue_id: params[:data][:issue_id] ).first
		if data.blank?
			render :json => {status: 0, message: "No record found"}
		else
			p=data.build_payment
			p.store_id = params[:store_id]
			p.transaction_id = params[:data][:transaction_id]
			p.amount = params[:data][:amount]
			if p.save
				render :json => {status: 1}
			else
				render :json => {status: 0}
			end
		end
	end

	private
	def check_auth_token
		@user = User.find_by_auth_token(params["authtoken"])
		raise if @user.blank?
		rescue Exception => e
			render :json => {message: "No User Found", status: 0}
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	# skip_before_filter  :verify_authenticity_token, only: [:submit_quote]

	def authenticate
	    callback = quickbooks_oauth_callback_url
	    token = QB_OAUTH_CONSUMER.get_request_token(:oauth_callback => callback)
	    session[:qb_request_token] = token
	    redirect_to("https://a''ppcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
	end

	def oauth_callback
		at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
		token = at.token
		secret = at.secret
		realm_id = params['realmId']
		# store the token, secret & RealmID somewhere for this user, you will need all 3 to work with Quickbooks-Ruby
	end

	def index
  		# if current_user.admin?
  			@users = User.all #.where(admin: false)
	  	# else
	  		# @user = current_user
	  	# end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_index_url, notice: "User was successfully created."
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @user.update(user_params)
	    	redirect_to user_index_url, notice: 'User was successfully updated.'
	    else
	    	render :edit
	    end
	end

	def show
		
	end

	def destroy
		@user.destroy
		redirect_to user_index_url, notice: 'User was successfully deleted.'
	end

	def report
    	@users = User.all.where(admin: false)
    	@stores = Store.all
    	@issues = Issue.all
    	# binding.pry
    	
    end

    def excel
    	# @users = User.all.where(admin: false)
    	# @sales = Sale.order(:id)
    	# drop_qty = params[:drop_qty]
    	# pick_qty = params[:pick_qty]
    	# sale = params[:sale]
    	# issue = params[:issue]
    	# @params = drop_qty + " " + pick_qty + " " + sale + " " + issue
    	# @params = @params.split(" ")
    	@user = User.where(id: params[:user]).first
    	if @user.blank?
    		user_ids = User.where(admin: false).map(&:id)
    	else
    		user_ids = @user.id
    	end

    	@store = Store.where(id: params[:store]).first
    	if @store.blank?
    		store_ids = Store.all.map(&:id)
    	else
    		store_ids = @store.id
    	end

    	@issue = Issue.where(id: params[:issue]).first
    	if @issue.blank?
    		issue_ids = Issue.all.map(&:id)
    	else
    		issue_ids = @issue.id
    	end

    	# binding.pry
		# @result = Sale.where("created_at >= :start_date AND created_at <= :end_date", {start_date: params[:starting_date], end_date: params[:ending_date]})
    	@data = Sale.where(user_id: user_ids, store_id: store_ids , issue_id: issue_ids)#.group_by(&:issue_id)

    	@products = @data
    	binding.pry
		respond_to do |format|
			format.html
			format.csv { send_data @products.to_csv }
			format.xls { send_data @products.to_csv(col_sep: "\t") }
		end
    end

    def search
    	@user = User.where(id: params[:user]).first
    	if @user.blank?
    		user_ids = User.where(admin: false).map(&:id)
    	else
    		user_ids = @user.id
    	end

    	@store = Store.where(id: params[:store]).first
    	if @store.blank?
    		store_ids = Store.all.map(&:id)
    	else
    		store_ids = @store.id
    	end

    	@issue = Issue.where(id: params[:issue]).first
    	if @issue.blank?
    		issue_ids = Issue.all.map(&:id)
    	else
    		issue_ids = @issue.id
    	end

    	# binding.pry
		@result = Sale.where("created_at >= :start_date AND created_at <= :end_date", {start_date: params[:starting_date], end_date: params[:ending_date]})
    	@data = Sale.where(user_id: user_ids, store_id: store_ids , issue_id: issue_ids , id: @result.ids ).group_by(&:issue_id)
		# binding.pry
		

    end

	private

	def set_user
      @user = User.find(params[:id])
    end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<div class="page-header">
  <h1 class="page-title">Add Sale Staff</h1>
</div>
<div class="page-content">
  <div class="panel">
    <div class="panel-body">
      <%= form_for(@user,url: (@user.new_record? ? user_index_path : user_path), html: {class: "form-horizontal", id: "staff_form"}) do |f| %>
          <% if @user.errors.any? %>
            <div class="alert dark alert-danger alert-dismissible">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :email, class: "col-md-3 control-label" %>
            <div class="col-md-9">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>

          <% if @user.new_record? %>
            <div class="form-group">
              <%= f.label :password, class: "col-md-3 control-label" %>
              <div class="col-md-9">
                <%= f.password_field :password, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, class: "col-md-3 control-label" %>
              <div class="col-md-9">
                <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>
            </div>
          <%end%>

          <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
                  <%= f.submit (@user.new_record? ? "Submit" : "Update"), class: "btn btn-primary", id: "validateButton" %>
                   <%= link_to 'Back', user_index_path, class: "btn btn-primary", method: "get" %>
              </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#staff_form').formValidation({
      framework: "bootstrap",
      button: {
        selector: '#validateButton',
        disabled: 'disabled'
      },
      icon: null,
      fields: {
        "user[name]": {
          validators: {
            notEmpty: {
              message: 'The name is required and cannot be empty'
            }
          }
        },
        "user[email]": {
          validators: {
            notEmpty: {
              message: 'The email address is required and cannot be empty'
            },
            emailAddress: {
              message: 'The email address is not valid'
            }
          }
        },
        <% if @user.new_record? %>
        "user[password]": {
          validators: {
            notEmpty: {
              message: 'The password is required and cannot be empty'
            },
            stringLength: {
              min: 8,
              message: 'Password is too short (minimum is 8 characters)'
            },
            identical: {
              field: "user[password_confirmation]",
              message: 'The password and its confirm are not the same'
            }
          }
        },
        "user[password_confirmation]": {
          validators: {
            notEmpty: {
              message: 'The password confirmation is required and cannot be empty'
            },
            stringLength: {
              min: 8,
              message: 'Password is too short (minimum is 8 characters)'
            },
            identical: {
              field: "user[password]",
              message: 'The password and its confirm are not the same'
            }
          }
        }
        <%end%>
      }
    });
  })
</script>

app/views/user/_user_data.html.erb
<h1>Sales by <%=@user.blank? ? "All" : @user.name.humanize%></h1>



<table class="table">
	<th>Issue</th>
	<th>Drop Qty</th>
	<th>Pick Qty</th>
	<th>Sale</th>
	<% @data.each do |a,b| %>
		<tr>
			<% s = 0%>
			<% d = 0%>
			<% p = 0%>

			<%b.each do |c|%>
				<% d=d+c.drop_qty.to_i %>
				<% p=p+c.pick_qty.to_i %>
				<% s=s+(c.drop_qty.to_i - c.pick_qty.to_i) %>
			<%end%>

			<td><%=Issue.where(id: a).first.try(:name)%></td>
			<td><%=d%></td>
			<td><%=p%></td>
			<td><%=s%></td>
		</tr>
	<%end%>
</table>

app/views/user/excel.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Issue</Data></Cell>
        <Cell><Data ss:Type="String">Drop Qty</Data></Cell>
        <Cell><Data ss:Type="String">Pick Qty</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.issue_id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.drop_qty %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.pick_qty %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/user/index.html.erb
<%# if current_user && current_user.admin? %>
    <div class="page-header">
      <h1 class="page-title">Sales Staff <%= link_to 'Add Staff', new_user_path, class: "btn btn-primary pull-right", method: :get %></h1>
    </div>
    <div class="page-content">
    	<div class="panel">
	        <div class="panel-body">
	        	<table class="table table-hover dataTable table-striped width-full" data-plugin="dataTable" id="staff_table">
		            <thead>
		              <tr>
		                <th>Name</th>
						<th>Email</th>
						<th>Actions</th>
						<th>Actions</th>
		              </tr>
		            </thead>
		            <tbody>
		            	<% @users.each do |u| %>
							<tr>
								<td><%= u.name %></td>
								<td><%= u.email %></td>
								<td><%= link_to 'Edit', edit_user_path(u), method: :get %></td>
						        <td><%= link_to 'Delete', user_path(u), method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr>
						<% end %>
	            	</tbody>
	          	</table>
	        </div>
      	</div>
    </div>
<%#end%>

<script type="text/javascript">
	// $(document).ready(function(){
	// 	$("#staff_table").DataTable( {
	// 	    responsive: true
	// 	} );
	// })
</script>

app/views/user/report.html.erb
<div class="page-content">
  <div class="panel">
    <div class="panel-body">
      

      <%= form_tag "/user/search", method: "get", class: "form-horizontal", remote: true do %>

          <div class="form-group">
            <label class="col-md-3 control-label">Select Store</label>
            <div class="col-md-9">
              <% stores = @stores.map{|a| ["#{a.name}", a.id] } %>
              <% stores = stores.unshift(['All Stores', 0]) %>
              <%= select_tag :store,options_for_select(stores), { class: "form-control"} %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-3 control-label">Select User</label>
            <div class="col-md-9">
              <% users = @users.map{|a| ["#{a.name}", a.id] } %>
              <%# users = users.unshift(['All Users', 0]) %>
              <%= select_tag :user,options_for_select(users), {prompt: "Select User", class: "form-control"} %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-3 control-label">Select Issue</label>
            <div class="col-md-9">
              <% issues = @issues.map{|a| ["#{a.name}", a.id] } %>
              <%# users = users.unshift(['All Users', 0]) %>
              <%= select_tag :issue,options_for_select(issues), {prompt: "Select Issues", class: "form-control"} %>
            </div>
          </div>

          <div class="form-group">
            <label for="Starting Date" class="col-md-3 col-xs-6 control-label" style="margin-top:20px;"> Starting Date </label>
            <div class="col-md-3 col-xs-6" style="margin-top:20px;">
              <%= date_field_tag( :starting_date ) %>
            </div>
            <label for="Etarting Date" class="col-md-3 col-xs-6 control-label" style="margin-top:20px;"> Ending Date </label>
            <div class="col-md-3 col-xs-6" style="margin-top:20px;">
              <%= date_field_tag( :ending_date ) %>
            </div>
          </div>
          <hr/>
          <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <p>
                  Download:
                  <%= link_to "CSV",  excel_user_index_path(format: "csv" ) %> |
                  <%= link_to "Excel",  excel_user_index_path(format: "xls") %>
                </p>
            </div>
          </div>

          <div class="form-group">
              <div class="col-md-offset-3 col-md-9">
                  <%= submit_tag "Search", class: "btn btn-primary" %>
                  <%= link_to 'Back', user_index_path, class: "btn btn-primary", method: "get" %>
              </div>
          </div>
          
          <hr/>
          <div class="user_data">
              
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/search.js.erb
$(".user_data").html("<%= escape_javascript( render( :partial => 'user_data', :locals => { } ) ) %>")

app/views/user/show.html.erb
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @user.name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @user.email %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', user_index_path %>
</div>